### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by fhp** [pimatic/pimatic.org#1]
The github link is misspelled for the dht-sensors plugin on [https://pimatic.org/plugins/pimatic-dht-sensors/](https://pimatic.org/plugins/pimatic-dht-sensors/) (the S and N in sensors are swapped).

**Comment by mwittig** [comment]
@fhp I think this has been fixed. Can you confirm this?

**Comment by fhp** [comment]
Yes looks good now.
